// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

const (
	UploadSecretScopes uploadSecretContextKey = "UploadSecret.Scopes"
)

// Defines values for VideoStatus.
const (
	Failed     VideoStatus = "failed"
	Processing VideoStatus = "processing"
	Ready      VideoStatus = "ready"
	Uploading  VideoStatus = "uploading"
)

// Valid indicates whether the value is a known member of the VideoStatus enum.
func (e VideoStatus) Valid() bool {
	switch e {
	case Failed:
		return true
	case Processing:
		return true
	case Ready:
		return true
	case Uploading:
		return true
	default:
		return false
	}
}

// ChunkStatus defines model for ChunkStatus.
type ChunkStatus struct {
	// ETag ETag returned by S3 after the part was uploaded; empty if not yet uploaded
	ETag       *string `json:"eTag,omitempty"`
	PartNumber int     `json:"partNumber"`
	Uploaded   bool    `json:"uploaded"`
}

// CompleteUploadRequest defines model for CompleteUploadRequest.
type CompleteUploadRequest struct {
	UploadId string `json:"uploadId"`
}

// ConfirmChunkRequest defines model for ConfirmChunkRequest.
type ConfirmChunkRequest struct {
	ETag       string `json:"eTag"`
	PartNumber int    `json:"partNumber"`
}

// ConfirmChunkResponse defines model for ConfirmChunkResponse.
type ConfirmChunkResponse struct {
	// Done True when this was the last chunk
	Done bool `json:"done"`

	// NextPartNumber Present only when done is false
	NextPartNumber *int `json:"nextPartNumber,omitempty"`

	// PartNumber The part number that was just confirmed
	PartNumber int `json:"partNumber"`

	// PresignedUrl Presigned PUT URL for the next part; absent when done is true
	PresignedUrl *string `json:"presignedUrl,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// UploadInitRequest defines model for UploadInitRequest.
type UploadInitRequest struct {
	Description string `json:"description"`

	// FileSize Total file size in bytes. Must be ≤ 104857600 (100MB)
	FileSize int64  `json:"fileSize"`
	Title    string `json:"title"`

	// TotalChunks Total number of chunks the client will upload
	TotalChunks int `json:"totalChunks"`

	// VideoId Omit for new uploads; provide to resume an existing upload
	VideoId *string `json:"videoId,omitempty"`
}

// UploadInitResponse defines model for UploadInitResponse.
type UploadInitResponse struct {
	Chunks []ChunkStatus `json:"chunks"`

	// NextPartNumber Part number for which the presignedUrl is issued
	NextPartNumber int `json:"nextPartNumber"`

	// PresignedUrl S3 presigned PUT URL for the next chunk
	PresignedUrl string `json:"presignedUrl"`

	// UploadId S3 multipart upload ID
	UploadId string `json:"uploadId"`
	VideoId  string `json:"videoId"`
}

// VideoDetail defines model for VideoDetail.
type VideoDetail struct {
	Description string `json:"description"`

	// ManifestUrl CloudFront HLS master manifest URL; present only when status is ready
	ManifestUrl *string     `json:"manifestUrl,omitempty"`
	Status      VideoStatus `json:"status"`

	// ThumbnailUrl CloudFront thumbnail URL; present only when status is ready
	ThumbnailUrl *string   `json:"thumbnailUrl,omitempty"`
	Title        string    `json:"title"`
	UploadedAt   time.Time `json:"uploadedAt"`
	VideoId      string    `json:"videoId"`
}

// VideoStatus defines model for VideoStatus.
type VideoStatus string

// VideoSummary defines model for VideoSummary.
type VideoSummary struct {
	Status       VideoStatus `json:"status"`
	ThumbnailUrl string      `json:"thumbnailUrl"`
	Title        string      `json:"title"`
	UploadedAt   time.Time   `json:"uploadedAt"`
	VideoId      string      `json:"videoId"`
}

// uploadSecretContextKey is the context key for UploadSecret security scheme
type uploadSecretContextKey string

// InitUploadJSONRequestBody defines body for InitUpload for application/json ContentType.
type InitUploadJSONRequestBody = UploadInitRequest

// CompleteUploadJSONRequestBody defines body for CompleteUpload for application/json ContentType.
type CompleteUploadJSONRequestBody = CompleteUploadRequest

// ConfirmChunkJSONRequestBody defines body for ConfirmChunk for application/json ContentType.
type ConfirmChunkJSONRequestBody = ConfirmChunkRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all ready videos
	// (GET /videos)
	GetVideos(w http.ResponseWriter, r *http.Request)
	// Initiate or resume a multipart upload
	// (POST /videos/upload/init)
	InitUpload(w http.ResponseWriter, r *http.Request)
	// Get video metadata
	// (GET /videos/{videoId})
	GetVideo(w http.ResponseWriter, r *http.Request, videoId string)
	// Finalise the multipart upload
	// (POST /videos/{videoId}/upload/complete)
	CompleteUpload(w http.ResponseWriter, r *http.Request, videoId string)
	// Confirm a successfully uploaded chunk and get the next presigned URL
	// (POST /videos/{videoId}/upload/confirm-chunk)
	ConfirmChunk(w http.ResponseWriter, r *http.Request, videoId string)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List all ready videos
// (GET /videos)
func (_ Unimplemented) GetVideos(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initiate or resume a multipart upload
// (POST /videos/upload/init)
func (_ Unimplemented) InitUpload(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get video metadata
// (GET /videos/{videoId})
func (_ Unimplemented) GetVideo(w http.ResponseWriter, r *http.Request, videoId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Finalise the multipart upload
// (POST /videos/{videoId}/upload/complete)
func (_ Unimplemented) CompleteUpload(w http.ResponseWriter, r *http.Request, videoId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Confirm a successfully uploaded chunk and get the next presigned URL
// (POST /videos/{videoId}/upload/confirm-chunk)
func (_ Unimplemented) ConfirmChunk(w http.ResponseWriter, r *http.Request, videoId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetVideos operation middleware
func (siw *ServerInterfaceWrapper) GetVideos(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVideos(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// InitUpload operation middleware
func (siw *ServerInterfaceWrapper) InitUpload(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, UploadSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.InitUpload(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetVideo operation middleware
func (siw *ServerInterfaceWrapper) GetVideo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "videoId" -------------
	var videoId string

	err = runtime.BindStyledParameterWithOptions("simple", "videoId", chi.URLParam(r, "videoId"), &videoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "videoId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetVideo(w, r, videoId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CompleteUpload operation middleware
func (siw *ServerInterfaceWrapper) CompleteUpload(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "videoId" -------------
	var videoId string

	err = runtime.BindStyledParameterWithOptions("simple", "videoId", chi.URLParam(r, "videoId"), &videoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "videoId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, UploadSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CompleteUpload(w, r, videoId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmChunk operation middleware
func (siw *ServerInterfaceWrapper) ConfirmChunk(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "videoId" -------------
	var videoId string

	err = runtime.BindStyledParameterWithOptions("simple", "videoId", chi.URLParam(r, "videoId"), &videoId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "videoId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, UploadSecretScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmChunk(w, r, videoId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/videos", wrapper.GetVideos)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/videos/upload/init", wrapper.InitUpload)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/videos/{videoId}", wrapper.GetVideo)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/videos/{videoId}/upload/complete", wrapper.CompleteUpload)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/videos/{videoId}/upload/confirm-chunk", wrapper.ConfirmChunk)
	})

	return r
}

type GetVideosRequestObject struct {
}

type GetVideosResponseObject interface {
	VisitGetVideosResponse(w http.ResponseWriter) error
}

type GetVideos200JSONResponse []VideoSummary

func (response GetVideos200JSONResponse) VisitGetVideosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVideos500JSONResponse ErrorResponse

func (response GetVideos500JSONResponse) VisitGetVideosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type InitUploadRequestObject struct {
	Body *InitUploadJSONRequestBody
}

type InitUploadResponseObject interface {
	VisitInitUploadResponse(w http.ResponseWriter) error
}

type InitUpload200JSONResponse UploadInitResponse

func (response InitUpload200JSONResponse) VisitInitUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type InitUpload400JSONResponse ErrorResponse

func (response InitUpload400JSONResponse) VisitInitUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type InitUpload401JSONResponse ErrorResponse

func (response InitUpload401JSONResponse) VisitInitUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetVideoRequestObject struct {
	VideoId string `json:"videoId"`
}

type GetVideoResponseObject interface {
	VisitGetVideoResponse(w http.ResponseWriter) error
}

type GetVideo200JSONResponse VideoDetail

func (response GetVideo200JSONResponse) VisitGetVideoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetVideo404JSONResponse ErrorResponse

func (response GetVideo404JSONResponse) VisitGetVideoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteUploadRequestObject struct {
	VideoId string `json:"videoId"`
	Body    *CompleteUploadJSONRequestBody
}

type CompleteUploadResponseObject interface {
	VisitCompleteUploadResponse(w http.ResponseWriter) error
}

type CompleteUpload200Response struct {
}

func (response CompleteUpload200Response) VisitCompleteUploadResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type CompleteUpload401JSONResponse ErrorResponse

func (response CompleteUpload401JSONResponse) VisitCompleteUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CompleteUpload404JSONResponse ErrorResponse

func (response CompleteUpload404JSONResponse) VisitCompleteUploadResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmChunkRequestObject struct {
	VideoId string `json:"videoId"`
	Body    *ConfirmChunkJSONRequestBody
}

type ConfirmChunkResponseObject interface {
	VisitConfirmChunkResponse(w http.ResponseWriter) error
}

type ConfirmChunk200JSONResponse ConfirmChunkResponse

func (response ConfirmChunk200JSONResponse) VisitConfirmChunkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmChunk401JSONResponse ErrorResponse

func (response ConfirmChunk401JSONResponse) VisitConfirmChunkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ConfirmChunk404JSONResponse ErrorResponse

func (response ConfirmChunk404JSONResponse) VisitConfirmChunkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// List all ready videos
	// (GET /videos)
	GetVideos(ctx context.Context, request GetVideosRequestObject) (GetVideosResponseObject, error)
	// Initiate or resume a multipart upload
	// (POST /videos/upload/init)
	InitUpload(ctx context.Context, request InitUploadRequestObject) (InitUploadResponseObject, error)
	// Get video metadata
	// (GET /videos/{videoId})
	GetVideo(ctx context.Context, request GetVideoRequestObject) (GetVideoResponseObject, error)
	// Finalise the multipart upload
	// (POST /videos/{videoId}/upload/complete)
	CompleteUpload(ctx context.Context, request CompleteUploadRequestObject) (CompleteUploadResponseObject, error)
	// Confirm a successfully uploaded chunk and get the next presigned URL
	// (POST /videos/{videoId}/upload/confirm-chunk)
	ConfirmChunk(ctx context.Context, request ConfirmChunkRequestObject) (ConfirmChunkResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetVideos operation middleware
func (sh *strictHandler) GetVideos(w http.ResponseWriter, r *http.Request) {
	var request GetVideosRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVideos(ctx, request.(GetVideosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVideos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVideosResponseObject); ok {
		if err := validResponse.VisitGetVideosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// InitUpload operation middleware
func (sh *strictHandler) InitUpload(w http.ResponseWriter, r *http.Request) {
	var request InitUploadRequestObject

	var body InitUploadJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.InitUpload(ctx, request.(InitUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "InitUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(InitUploadResponseObject); ok {
		if err := validResponse.VisitInitUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetVideo operation middleware
func (sh *strictHandler) GetVideo(w http.ResponseWriter, r *http.Request, videoId string) {
	var request GetVideoRequestObject

	request.VideoId = videoId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetVideo(ctx, request.(GetVideoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetVideo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetVideoResponseObject); ok {
		if err := validResponse.VisitGetVideoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CompleteUpload operation middleware
func (sh *strictHandler) CompleteUpload(w http.ResponseWriter, r *http.Request, videoId string) {
	var request CompleteUploadRequestObject

	request.VideoId = videoId

	var body CompleteUploadJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CompleteUpload(ctx, request.(CompleteUploadRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CompleteUpload")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CompleteUploadResponseObject); ok {
		if err := validResponse.VisitCompleteUploadResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ConfirmChunk operation middleware
func (sh *strictHandler) ConfirmChunk(w http.ResponseWriter, r *http.Request, videoId string) {
	var request ConfirmChunkRequestObject

	request.VideoId = videoId

	var body ConfirmChunkJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ConfirmChunk(ctx, request.(ConfirmChunkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ConfirmChunk")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ConfirmChunkResponseObject); ok {
		if err := validResponse.VisitConfirmChunkResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
