quiet: true
disable-version-string: true
with-expecter: true
issue-845-fix: true
outpkg: mocks
dir: internal/mocks
packages:
  github.com/lregnier/design-youtube/api/internal/domain/video:
    interfaces:
      VideoRepository:
  github.com/lregnier/design-youtube/api/internal/ports:
    interfaces:
      ObjectStore:
      Cache:
