version: "3.9"

services:
  api:
    build:
      context: ./backend/api
      dockerfile: Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      UPLOAD_SECRET: devsecret
      AWS_REGION: us-east-1
      DYNAMODB_TABLE: videos
      S3_BUCKET: design-youtube-video-prod
      CLOUDFRONT_DOMAIN: localhost
      SQS_QUEUE_URL: http://localstack:4566/000000000000/video-processing.fifo
      RESULTS_QUEUE_URL: http://localstack:4566/000000000000/video-processing-results.fifo
      REDIS_ADDR: redis:6379
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
      S3_PUBLIC_ENDPOINT_URL: http://localhost:4566
      S3_USE_PATH_STYLE: "true"
      CORS_ALLOWED_ORIGINS: "*"
    depends_on:
      - redis
      - localstack

  worker:
    build:
      context: ./backend/worker
      dockerfile: Dockerfile
    environment:
      AWS_REGION: us-east-1
      S3_BUCKET: design-youtube-video-prod
      CLOUDFRONT_DOMAIN: localhost
      SQS_QUEUE_URL: http://localstack:4566/000000000000/video-processing.fifo
      RESULTS_QUEUE_URL: http://localstack:4566/000000000000/video-processing-results.fifo
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_ENDPOINT_URL: http://localstack:4566
    depends_on:
      - localstack

  frontend:
    build:
      context: ./frontend/web
    ports:
      - "3000:80"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack:3
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs,dynamodb
      DEFAULT_REGION: us-east-1
