/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all ready videos */
        get: operations["GetVideos"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{videoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get video metadata */
        get: operations["GetVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/upload/init": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Initiate or resume a multipart upload */
        post: operations["InitUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{videoId}/upload/confirm-chunk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm a successfully uploaded chunk and get the next presigned URL */
        post: operations["ConfirmChunk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{videoId}/upload/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalise the multipart upload */
        post: operations["CompleteUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UploadInitRequest: {
            /** @description Omit for new uploads; provide to resume an existing upload */
            videoId?: string;
            title: string;
            description: string;
            /**
             * Format: int64
             * @description Total file size in bytes. Must be ≤ 104857600 (100MB)
             */
            fileSize: number;
            /** @description Total number of chunks the client will upload */
            totalChunks: number;
        };
        ChunkStatus: {
            partNumber: number;
            uploaded: boolean;
            /** @description ETag returned by S3 after the part was uploaded; empty if not yet uploaded */
            eTag?: string;
        };
        UploadInitResponse: {
            videoId: string;
            /** @description S3 multipart upload ID */
            uploadId: string;
            /** @description Part number for which the presignedUrl is issued */
            nextPartNumber: number;
            /** @description S3 presigned PUT URL for the next chunk */
            presignedUrl: string;
            chunks: components["schemas"]["ChunkStatus"][];
        };
        ConfirmChunkRequest: {
            partNumber: number;
            eTag: string;
        };
        ConfirmChunkResponse: {
            /** @description The part number that was just confirmed */
            partNumber: number;
            /** @description True when this was the last chunk */
            done: boolean;
            /** @description Present only when done is false */
            nextPartNumber?: number;
            /** @description Presigned PUT URL for the next part; absent when done is true */
            presignedUrl?: string;
        };
        CompleteUploadRequest: {
            uploadId: string;
        };
        /** @enum {string} */
        VideoStatus: "uploading" | "processing" | "ready" | "failed";
        VideoSummary: {
            videoId: string;
            title: string;
            thumbnailUrl: string;
            /** Format: date-time */
            uploadedAt: string;
            status: components["schemas"]["VideoStatus"];
        };
        VideoDetail: {
            videoId: string;
            title: string;
            description: string;
            status: components["schemas"]["VideoStatus"];
            /** Format: date-time */
            uploadedAt: string;
            /** @description CloudFront HLS master manifest URL; present only when status is ready */
            manifestUrl?: string;
            /** @description CloudFront thumbnail URL; present only when status is ready */
            thumbnailUrl?: string;
        };
        ErrorResponse: {
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetVideos: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of video summaries ordered newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoSummary"][];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    GetVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                videoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Video metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VideoDetail"];
                };
            };
            /** @description Video not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    InitUpload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadInitRequest"];
            };
        };
        responses: {
            /** @description Upload initiated or resumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadInitResponse"];
                };
            };
            /** @description Invalid request (e.g. file too large) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid upload secret */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    ConfirmChunk: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                videoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmChunkRequest"];
            };
        };
        responses: {
            /** @description Chunk confirmed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfirmChunkResponse"];
                };
            };
            /** @description Missing or invalid upload secret */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Video not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    CompleteUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                videoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteUploadRequest"];
            };
        };
        responses: {
            /** @description Upload completed, processing started */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid upload secret */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Video not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
