include classpath("application.conf")

node-address {
  protocol = http
  host = "*"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  "video-processing.fifo" {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    fifo = true
    contentBasedDeduplication = true
  }
  "video-processing-results.fifo" {
    defaultVisibilityTimeout = 10 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
    fifo = true
    contentBasedDeduplication = true
  }
}

aws {
  accountId = "000000000000"
  region = "us-east-1"
}
