quiet: true
disable-version-string: true
with-expecter: true
issue-845-fix: true
outpkg: mocks
dir: gen/mocks
packages:
  github.com/lregnier/design-youtube/worker/internal/application:
    interfaces:
      VideoStorage:
      Transcoder:
      EventPublisher:
      VideoProcessingService:
