quiet: true
disable-version-string: true
with-expecter: true
issue-845-fix: true
outpkg: mocks
dir: internal/mocks
packages:
  github.com/lregnier/design-youtube/worker/internal/ports:
    interfaces:
      VideoStorage:
      Transcoder:
      ResultPublisher:
