// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockVideoStorage is an autogenerated mock type for the VideoStorage type
type MockVideoStorage struct {
	mock.Mock
}

type MockVideoStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVideoStorage) EXPECT() *MockVideoStorage_Expecter {
	return &MockVideoStorage_Expecter{mock: &_m.Mock}
}

// DownloadRaw provides a mock function with given fields: ctx, videoID, destPath
func (_m *MockVideoStorage) DownloadRaw(ctx context.Context, videoID string, destPath string) error {
	ret := _m.Called(ctx, videoID, destPath)

	if len(ret) == 0 {
		panic("no return value specified for DownloadRaw")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, videoID, destPath)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVideoStorage_DownloadRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadRaw'
type MockVideoStorage_DownloadRaw_Call struct {
	*mock.Call
}

// DownloadRaw is a helper method to define mock.On call
//   - ctx context.Context
//   - videoID string
//   - destPath string
func (_e *MockVideoStorage_Expecter) DownloadRaw(ctx interface{}, videoID interface{}, destPath interface{}) *MockVideoStorage_DownloadRaw_Call {
	return &MockVideoStorage_DownloadRaw_Call{Call: _e.mock.On("DownloadRaw", ctx, videoID, destPath)}
}

func (_c *MockVideoStorage_DownloadRaw_Call) Run(run func(ctx context.Context, videoID string, destPath string)) *MockVideoStorage_DownloadRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVideoStorage_DownloadRaw_Call) Return(_a0 error) *MockVideoStorage_DownloadRaw_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVideoStorage_DownloadRaw_Call) RunAndReturn(run func(context.Context, string, string) error) *MockVideoStorage_DownloadRaw_Call {
	_c.Call.Return(run)
	return _c
}

// UploadManifest provides a mock function with given fields: ctx, videoID, content
func (_m *MockVideoStorage) UploadManifest(ctx context.Context, videoID string, content []byte) (string, error) {
	ret := _m.Called(ctx, videoID, content)

	if len(ret) == 0 {
		panic("no return value specified for UploadManifest")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return rf(ctx, videoID, content)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = rf(ctx, videoID, content)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, videoID, content)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVideoStorage_UploadManifest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadManifest'
type MockVideoStorage_UploadManifest_Call struct {
	*mock.Call
}

// UploadManifest is a helper method to define mock.On call
//   - ctx context.Context
//   - videoID string
//   - content []byte
func (_e *MockVideoStorage_Expecter) UploadManifest(ctx interface{}, videoID interface{}, content interface{}) *MockVideoStorage_UploadManifest_Call {
	return &MockVideoStorage_UploadManifest_Call{Call: _e.mock.On("UploadManifest", ctx, videoID, content)}
}

func (_c *MockVideoStorage_UploadManifest_Call) Run(run func(ctx context.Context, videoID string, content []byte)) *MockVideoStorage_UploadManifest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockVideoStorage_UploadManifest_Call) Return(cloudfrontURL string, err error) *MockVideoStorage_UploadManifest_Call {
	_c.Call.Return(cloudfrontURL, err)
	return _c
}

func (_c *MockVideoStorage_UploadManifest_Call) RunAndReturn(run func(context.Context, string, []byte) (string, error)) *MockVideoStorage_UploadManifest_Call {
	_c.Call.Return(run)
	return _c
}

// UploadSegments provides a mock function with given fields: ctx, videoID, segDir
func (_m *MockVideoStorage) UploadSegments(ctx context.Context, videoID string, segDir string) error {
	ret := _m.Called(ctx, videoID, segDir)

	if len(ret) == 0 {
		panic("no return value specified for UploadSegments")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, videoID, segDir)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVideoStorage_UploadSegments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadSegments'
type MockVideoStorage_UploadSegments_Call struct {
	*mock.Call
}

// UploadSegments is a helper method to define mock.On call
//   - ctx context.Context
//   - videoID string
//   - segDir string
func (_e *MockVideoStorage_Expecter) UploadSegments(ctx interface{}, videoID interface{}, segDir interface{}) *MockVideoStorage_UploadSegments_Call {
	return &MockVideoStorage_UploadSegments_Call{Call: _e.mock.On("UploadSegments", ctx, videoID, segDir)}
}

func (_c *MockVideoStorage_UploadSegments_Call) Run(run func(ctx context.Context, videoID string, segDir string)) *MockVideoStorage_UploadSegments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockVideoStorage_UploadSegments_Call) Return(_a0 error) *MockVideoStorage_UploadSegments_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVideoStorage_UploadSegments_Call) RunAndReturn(run func(context.Context, string, string) error) *MockVideoStorage_UploadSegments_Call {
	_c.Call.Return(run)
	return _c
}

// UploadThumbnail provides a mock function with given fields: ctx, videoID, data
func (_m *MockVideoStorage) UploadThumbnail(ctx context.Context, videoID string, data []byte) (string, error) {
	ret := _m.Called(ctx, videoID, data)

	if len(ret) == 0 {
		panic("no return value specified for UploadThumbnail")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) (string, error)); ok {
		return rf(ctx, videoID, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) string); ok {
		r0 = rf(ctx, videoID, data)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []byte) error); ok {
		r1 = rf(ctx, videoID, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockVideoStorage_UploadThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadThumbnail'
type MockVideoStorage_UploadThumbnail_Call struct {
	*mock.Call
}

// UploadThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - videoID string
//   - data []byte
func (_e *MockVideoStorage_Expecter) UploadThumbnail(ctx interface{}, videoID interface{}, data interface{}) *MockVideoStorage_UploadThumbnail_Call {
	return &MockVideoStorage_UploadThumbnail_Call{Call: _e.mock.On("UploadThumbnail", ctx, videoID, data)}
}

func (_c *MockVideoStorage_UploadThumbnail_Call) Run(run func(ctx context.Context, videoID string, data []byte)) *MockVideoStorage_UploadThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockVideoStorage_UploadThumbnail_Call) Return(cloudfrontURL string, err error) *MockVideoStorage_UploadThumbnail_Call {
	_c.Call.Return(cloudfrontURL, err)
	return _c
}

func (_c *MockVideoStorage_UploadThumbnail_Call) RunAndReturn(run func(context.Context, string, []byte) (string, error)) *MockVideoStorage_UploadThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVideoStorage creates a new instance of MockVideoStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVideoStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVideoStorage {
	mock := &MockVideoStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
