// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTranscoder is an autogenerated mock type for the Transcoder type
type MockTranscoder struct {
	mock.Mock
}

type MockTranscoder_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTranscoder) EXPECT() *MockTranscoder_Expecter {
	return &MockTranscoder_Expecter{mock: &_m.Mock}
}

// Duration provides a mock function with given fields: ctx, inputPath
func (_m *MockTranscoder) Duration(ctx context.Context, inputPath string) (float64, error) {
	ret := _m.Called(ctx, inputPath)

	if len(ret) == 0 {
		panic("no return value specified for Duration")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (float64, error)); ok {
		return rf(ctx, inputPath)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) float64); ok {
		r0 = rf(ctx, inputPath)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, inputPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTranscoder_Duration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Duration'
type MockTranscoder_Duration_Call struct {
	*mock.Call
}

// Duration is a helper method to define mock.On call
//   - ctx context.Context
//   - inputPath string
func (_e *MockTranscoder_Expecter) Duration(ctx interface{}, inputPath interface{}) *MockTranscoder_Duration_Call {
	return &MockTranscoder_Duration_Call{Call: _e.mock.On("Duration", ctx, inputPath)}
}

func (_c *MockTranscoder_Duration_Call) Run(run func(ctx context.Context, inputPath string)) *MockTranscoder_Duration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTranscoder_Duration_Call) Return(_a0 float64, _a1 error) *MockTranscoder_Duration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTranscoder_Duration_Call) RunAndReturn(run func(context.Context, string) (float64, error)) *MockTranscoder_Duration_Call {
	_c.Call.Return(run)
	return _c
}

// ExtractThumbnail provides a mock function with given fields: ctx, inputPath, offset
func (_m *MockTranscoder) ExtractThumbnail(ctx context.Context, inputPath string, offset float64) ([]byte, error) {
	ret := _m.Called(ctx, inputPath, offset)

	if len(ret) == 0 {
		panic("no return value specified for ExtractThumbnail")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) ([]byte, error)); ok {
		return rf(ctx, inputPath, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) []byte); ok {
		r0 = rf(ctx, inputPath, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, float64) error); ok {
		r1 = rf(ctx, inputPath, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTranscoder_ExtractThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractThumbnail'
type MockTranscoder_ExtractThumbnail_Call struct {
	*mock.Call
}

// ExtractThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - inputPath string
//   - offset float64
func (_e *MockTranscoder_Expecter) ExtractThumbnail(ctx interface{}, inputPath interface{}, offset interface{}) *MockTranscoder_ExtractThumbnail_Call {
	return &MockTranscoder_ExtractThumbnail_Call{Call: _e.mock.On("ExtractThumbnail", ctx, inputPath, offset)}
}

func (_c *MockTranscoder_ExtractThumbnail_Call) Run(run func(ctx context.Context, inputPath string, offset float64)) *MockTranscoder_ExtractThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64))
	})
	return _c
}

func (_c *MockTranscoder_ExtractThumbnail_Call) Return(_a0 []byte, _a1 error) *MockTranscoder_ExtractThumbnail_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTranscoder_ExtractThumbnail_Call) RunAndReturn(run func(context.Context, string, float64) ([]byte, error)) *MockTranscoder_ExtractThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// TranscodeHLS provides a mock function with given fields: ctx, inputPath, outputDir, scale, bitrate
func (_m *MockTranscoder) TranscodeHLS(ctx context.Context, inputPath string, outputDir string, scale string, bitrate string) error {
	ret := _m.Called(ctx, inputPath, outputDir, scale, bitrate)

	if len(ret) == 0 {
		panic("no return value specified for TranscodeHLS")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = rf(ctx, inputPath, outputDir, scale, bitrate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTranscoder_TranscodeHLS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TranscodeHLS'
type MockTranscoder_TranscodeHLS_Call struct {
	*mock.Call
}

// TranscodeHLS is a helper method to define mock.On call
//   - ctx context.Context
//   - inputPath string
//   - outputDir string
//   - scale string
//   - bitrate string
func (_e *MockTranscoder_Expecter) TranscodeHLS(ctx interface{}, inputPath interface{}, outputDir interface{}, scale interface{}, bitrate interface{}) *MockTranscoder_TranscodeHLS_Call {
	return &MockTranscoder_TranscodeHLS_Call{Call: _e.mock.On("TranscodeHLS", ctx, inputPath, outputDir, scale, bitrate)}
}

func (_c *MockTranscoder_TranscodeHLS_Call) Run(run func(ctx context.Context, inputPath string, outputDir string, scale string, bitrate string)) *MockTranscoder_TranscodeHLS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string))
	})
	return _c
}

func (_c *MockTranscoder_TranscodeHLS_Call) Return(_a0 error) *MockTranscoder_TranscodeHLS_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTranscoder_TranscodeHLS_Call) RunAndReturn(run func(context.Context, string, string, string, string) error) *MockTranscoder_TranscodeHLS_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTranscoder creates a new instance of MockTranscoder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTranscoder(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTranscoder {
	mock := &MockTranscoder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
