// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockResultPublisher is an autogenerated mock type for the ResultPublisher type
type MockResultPublisher struct {
	mock.Mock
}

type MockResultPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockResultPublisher) EXPECT() *MockResultPublisher_Expecter {
	return &MockResultPublisher_Expecter{mock: &_m.Mock}
}

// PublishFailed provides a mock function with given fields: ctx, videoID, reason
func (_m *MockResultPublisher) PublishFailed(ctx context.Context, videoID string, reason string) error {
	ret := _m.Called(ctx, videoID, reason)

	if len(ret) == 0 {
		panic("no return value specified for PublishFailed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, videoID, reason)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResultPublisher_PublishFailed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishFailed'
type MockResultPublisher_PublishFailed_Call struct {
	*mock.Call
}

// PublishFailed is a helper method to define mock.On call
//   - ctx context.Context
//   - videoID string
//   - reason string
func (_e *MockResultPublisher_Expecter) PublishFailed(ctx interface{}, videoID interface{}, reason interface{}) *MockResultPublisher_PublishFailed_Call {
	return &MockResultPublisher_PublishFailed_Call{Call: _e.mock.On("PublishFailed", ctx, videoID, reason)}
}

func (_c *MockResultPublisher_PublishFailed_Call) Run(run func(ctx context.Context, videoID string, reason string)) *MockResultPublisher_PublishFailed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockResultPublisher_PublishFailed_Call) Return(_a0 error) *MockResultPublisher_PublishFailed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResultPublisher_PublishFailed_Call) RunAndReturn(run func(context.Context, string, string) error) *MockResultPublisher_PublishFailed_Call {
	_c.Call.Return(run)
	return _c
}

// PublishProcessed provides a mock function with given fields: ctx, videoID, manifestURL, thumbnailURL
func (_m *MockResultPublisher) PublishProcessed(ctx context.Context, videoID string, manifestURL string, thumbnailURL string) error {
	ret := _m.Called(ctx, videoID, manifestURL, thumbnailURL)

	if len(ret) == 0 {
		panic("no return value specified for PublishProcessed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, videoID, manifestURL, thumbnailURL)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockResultPublisher_PublishProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishProcessed'
type MockResultPublisher_PublishProcessed_Call struct {
	*mock.Call
}

// PublishProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - videoID string
//   - manifestURL string
//   - thumbnailURL string
func (_e *MockResultPublisher_Expecter) PublishProcessed(ctx interface{}, videoID interface{}, manifestURL interface{}, thumbnailURL interface{}) *MockResultPublisher_PublishProcessed_Call {
	return &MockResultPublisher_PublishProcessed_Call{Call: _e.mock.On("PublishProcessed", ctx, videoID, manifestURL, thumbnailURL)}
}

func (_c *MockResultPublisher_PublishProcessed_Call) Run(run func(ctx context.Context, videoID string, manifestURL string, thumbnailURL string)) *MockResultPublisher_PublishProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockResultPublisher_PublishProcessed_Call) Return(_a0 error) *MockResultPublisher_PublishProcessed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockResultPublisher_PublishProcessed_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockResultPublisher_PublishProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockResultPublisher creates a new instance of MockResultPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockResultPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockResultPublisher {
	mock := &MockResultPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
